---
# vim: set ft=ansible:


- name: set ip_local_port_range
  become: yes
  become_user: root
  sysctl:
    name: net.ipv4.ip_local_port_range
    value: 10000 65000
    sysctl_set: yes
    state: present
    reload: yes

- name: create /etc/docker if missing
  become: yes
  become_user: root
  file:
    path: /etc/docker
    state: directory
    owner: root
    group: root
    mode: 0o700

- name: Docker daemon configuration file
  become: yes
  become_user: root
  template:
    src: daemon{{docker_conf_suffix}}.json.j2
    dest: /etc/docker/daemon.json

- name: mkdir /etc/systemd/system/docker.service.d
  become: yes
  become_user: root
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    owner: root
    group: root
    mode: 0o700

- name: set docker.service
  become: yes
  become_user: root
  copy:
    content: |
      [Unit]
      Description=Docker Application Container Engine
      Documentation=https://docs.docker.com
      After=network-online.target docker.socket firewalld.service containerd.service time-set.target
      Wants=network-online.target containerd.service
      Requires=docker.socket

      [Service]
      Type=notify
      # the default is not to use systemd for cgroups because the delegate issues still
      # exists and systemd currently does not support the cgroup feature set required
      # for containers run by docker
      ExecStart=/usr/bin/dockerd 
      ExecReload=/bin/kill -s HUP $MAINPID
      TimeoutStartSec=0
      RestartSec=2
      Restart=always

      # Note that StartLimit* options were moved from "Service" to "Unit" in systemd 229.
      # Both the old, and new location are accepted by systemd 229 and up, so using the old location
      # to make them work for either version of systemd.
      StartLimitBurst=3

      # Note that StartLimitInterval was renamed to StartLimitIntervalSec in systemd 230.
      # Both the old, and new name are accepted by systemd 230 and up, so using the old name to make
      # this option work for either version of systemd.
      StartLimitInterval=60s

      # Having non-zero Limit*s causes performance problems due to accounting overhead
      # in the kernel. We recommend using cgroups to do container-local accounting.
      LimitNOFILE=infinity
      LimitNPROC=infinity
      LimitCORE=infinity

      # Comment TasksMax if your systemd version does not support it.
      # Only systemd 226 and above support this option.
      TasksMax=infinity

      # set delegate yes so that systemd does not reset the cgroups of docker containers
      Delegate=yes

      # kill only the docker process, not all processes in the cgroup
      KillMode=process
      OOMScoreAdjust=-500

      [Install]
      WantedBy=multi-user.target
    dest: /etc/systemd/system/docker.service
    owner: root
    group: root
    mode: 0o600
  notify:
   - reload systemd  # need to do it ASAP
   - restart docker


- name: set docker.socket
  become: yes
  become_user: root
  copy:
    content: |
      [Unit]
      Description=Docker Socket for the API

      [Socket]
      # If /var/run is not implemented as a symlink to /run, you may need to
      # specify ListenStream=/var/run/docker.sock instead.
      ListenStream=/run/docker.sock
      SocketMode=0660
      SocketUser=root
      SocketGroup=docker

      [Install]
      WantedBy=sockets.target
    dest: /etc/systemd/system/docker.socket
    owner: root
    group: root
    mode: 0o600
  notify:
   - reload systemd  # need to do it ASAP
   - restart docker

# force systemd reload now, before installing docker, to avoid an apt error
- name: force systemd reload
  become: yes
  become_user: root
  command: systemctl daemon-reload
  tags:
    - always

