---
# vim: set ft=ansible:


- name: download docker
  get_url:
    url: https://download.docker.com/linux/static/stable/x86_64/docker-17.12.1-ce.tgz
    dest: "/tmp"
    mode: 0o600
  register: docker_download


- name: extract docker
  when: docker_download.changed
  command: tar xzvf docker-17.12.1-ce.tgz
  args:
    chdir: "/tmp"

- name: install docker
  become: yes
  become_user: root
  when: docker_download.changed
  command: cp docker/* /usr/bin/
  args:
    chdir: "/tmp"


- name: create docker group with users
  become: yes
  become_user: root
  command: groupadd docker

- name: add developer to docker group
  become: yes
  become_user: root
  command: usermod -aG docker developer 

- name: add ubuntu to docker group
  become: yes
  become_user: root
  command: usermod -aG docker ubuntu
