---
# vim: set ft=ansible:

- name: install python-pip
  become: yes
  become_user: root
  apt:
    name: "{{item}}"
    state: present
  with_items:
    - python-pip


- name: download docker compose
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-linux-x86_64
    dest: "/tmp"
    mode: 0o600
  register: dockerc_download

- name: install docker-compose
  become: yes
  become_user: root
  when: dockerc_download.changed
  command: cp docker-compose-linux-x86_64  /usr/local/bin/docker-compose && chmod +x  /usr/local/bin/docker-compose
  args:
    chdir: "/tmp"
